BEGIN TRANSACTION;

CREATE TABLE File (
    ID INTEGER PRIMARY KEY NOT NULL,
    Uploader INTEGER NOT NULL,
    Path TEXT NOT NULL,
    CreatedAt INTEGER NOT NULL,
    FOREIGN KEY (Uploader) REFERENCES User(ID)
);

CREATE TABLE User (
    ID INTEGER PRIMARY KEY NOT NULL,
    Username TEXT NOT NULL UNIQUE,
    Password TEXT NOT NULL,
    Link TEXT NOT NULL DEFAULT "",
    Email TEXT NOT NULL DEFAULT "",
    Name TEXT NOT NULL,
    Bio TEXT NOT NULL DEFAULT "",
    Experience TEXT NOT NULL DEFAULT "",
    Picture INTEGER DEFAULT NULL,
    IsMentor INTEGER NOT NULL DEFAULT 0,
        MentorAvailable INTEGER NOT NULL DEFAULT 0,
        MentorExpertise TEXT NOT NULL DEFAULT "",
    CreatedAt INTEGER NOT NULL,
    FOREIGN KEY (Picture) REFERENCES File(ID)
);

CREATE TABLE Mentorship (
    ID INTEGER PRIMARY KEY NOT NULL,
    Mentor INTEGER NOT NULL,
    Mentee INTEGER NOT NULL,
    CreatedAt INTEGER NOT NULL,
    EndedAt INTEGER DEFAULT NULL,
    FOREIGN KEY (Mentor) REFERENCES User(ID),
    FOREIGN KEY (Mentee) REFERENCES User(ID)
);

CREATE TABLE Blog (
    ID INTEGER PRIMARY KEY NOT NULL,
    Author INTEGER NOT NULL,
    Title TEXT NOT NULL,
    Content TEXT NOT NULL,
    CreatedAt INTEGER NOT NULL,
    FOREIGN KEY (Author) REFERENCES User(ID)
);

CREATE TABLE Startup (
    ID INTEGER PRIMARY KEY NOT NULL,
    Name TEXT NOT NULL,
    MissionStatement TEXT NOT NULL DEFAULT "",
    Offering TEXT NOT NULL DEFAULT "",
    Description TEXT NOT NULL DEFAULT "",
    Picture INTEGER DEFAULT NULL,
    CreatedAt INTEGER NOT NULL,
    FOREIGN KEY (Picture) REFERENCES File(ID)
);

CREATE TABLE Founder (
    ID INTEGER PRIMARY KEY NOT NULL,
    Founder INTEGER NOT NULL,
    Startup INTEGER NOT NULL,
    CreatedAt INTEGER NOT NULL,
    FOREIGN KEY (Founder) REFERENCES User(ID),
    FOREIGN KEY (Startup) REFERENCES Startup(ID),
    UNIQUE (Founder, Startup)
);

CREATE TABLE FollowUser (
    ID INTEGER PRIMARY KEY NOT NULL,
    Follower INTEGER NOT NULL,
    Following INTEGER NOT NULL,
    CreatedAt INTEGER NOT NULL,
    FOREIGN KEY (Follower) REFERENCES User(ID),
    FOREIGN KEY (Following) REFERENCES User(ID),
    UNIQUE (Follower, Following)
);

CREATE TABLE FollowStartup (
    ID INTEGER PRIMARY KEY NOT NULL,
    Follower INTEGER NOT NULL,
    Following INTEGER NOT NULL,
    CreatedAt INTEGER NOT NULL,
    FOREIGN KEY (Follower) REFERENCES User(ID),
    FOREIGN KEY (Following) REFERENCES Startup(ID),
    UNIQUE (Follower, Following)
);

END TRANSACTION;
